"""Add employee_id to onboardings table

Revision ID: 53f0a72cf76b
Revises: c701a0d3cfa5
Create Date: 2025-01-16 20:49:25.596519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53f0a72cf76b'
down_revision = 'c701a0d3cfa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted for batch mode ###
    with op.batch_alter_table('onboardings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_onboardings_employee_id_employees', 
            'employees', 
            ['employee_id'], 
            ['id']
        )

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_reviews_employee_id_employees', 
            'employees', 
            ['employee_id'], 
            ['id']
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - adjusted for batch mode ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('fk_reviews_employee_id_employees', type_='foreignkey')

    with op.batch_alter_table('onboardings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_onboardings_employee_id_employees', type_='foreignkey')
        batch_op.drop_column('employee_id')
    # ### end Alembic commands ###
